class Config:
    EAR_THRESHOLD = 0.23
    YAWN_RATIO_THRESHOLD = 0.22
    HAND_FACE_DISTANCE_THRESHOLD = 0.9

    WINDOW_SECONDS = 20

    TEMP_UP_ALPHA = 0.35
    TEMP_DOWN_ALPHA = 0.08

    ANOM_UP_ALPHA = 0.30
    ANOM_DOWN_ALPHA = 0.06